let handler = async (m, { conn, usedPrefix }) => conn.sendButton(m.chat, `“${bucin.getRandom()}”`, author, ['Bucin', `${usedPrefix}bucin`], m)

handler.help = ['bucin']
handler.tags = ['quotes']
handler.command = /^(bucin)$/i

export default handler


// https://jalantikus.com/tips/kata-kata-bucin/
const bucin = [
    "Elijo estar solo, no porque esté esperando al perfecto, sino porque necesito a alguien que nunca se rinda.",
    "Una sola persona se crea con una pareja que no ha encontrado.",
    "Soltero. Tal vez sea la manera de Dios de decir 'Descansa del amor equivocado'.",
    "Los solteros son jóvenes que priorizan su desarrollo personal para un amor con más clase más adelante.",
    "No estoy buscando a alguien que sea perfecto, pero estoy buscando a alguien que se vuelva perfecto debido a mis fortalezas.",
    "Los novios de las personas son nuestras almas gemelas pendientes.",
    "Los solteros deben pasar. Todo tiene un tiempo, cuando toda soledad se convierte en unión con un amante leal. Se paciente.",
    "Romeo estaba dispuesto a morir por Julieta, Jack murió por salvar a Rose. El punto es, si quieres vivir, sé soltero.",
    "Busco personas no por sus virtudes sino busco personas por su sinceridad.",
    "Jodoh bukan sendal jepit, que a menudo se confunden. Así que sigue estando en la lucha adecuada..",
    "Si eres las cuerdas de la guitarra, no quiero ser el guitarrista. Porque no quiero dejarte.",
    "Si amarte es una ilusión, entonces déjame imaginar para siempre.",
    "Cariño... Mi trabajo es solo amarte, no luchar contra el destino.",
    "Cuando estoy contigo, parece que 1 hora es solo 1 segundo, pero cuando estoy lejos de ti, parece que 1 día se convierte en 1 año.",
    "La compota de plátano sabe sumedang, aunque la distancia se alarga, mi amor nunca desaparecerá.",
    "Quiero ser el único, no el único.",
    "No puedo prometer ser bueno. Pero prometo estar siempre a tu lado.",
    "Si me convierto en un representante de la gente, definitivamente fallaré ¿Cómo puedo pensar en la gente si lo único que tengo en mente eres tú.",
    "Mira mi jardín, lleno de flores. Mira tus ojos, mi corazón está floreciendo.",
    "Promete quedarte conmigo ahora, mañana y para siempre.",
    "La añoranza no solo aparece por la distancia. Pero también por deseos no realizados.",
    "Nunca estarás lejos de mí, donde quiera que vaya siempre estás ahí, porque siempre estás en mi corazón, que está lejos solo de nuestro cuerpo, no de nuestro corazón.",
    "Sé en cada mirada que estamos obstaculizados por la distancia y el tiempo. Pero estoy seguro que luego podremos unirnos.",
    "Extrañarte sin conocerte nunca es lo mismo que crear una canción que nunca será cantada.",
    "Hay momentos en que la distancia siempre es una barrera entre tú y yo, pero aún así en mi corazón siempre estamos cerca.",
    "Si este corazón no puede contener todo el anhelo, no hay nada que pueda hacer por el",
    "Tal vez en este momento solo pueda sostener este anhelo. Hasta que llegue el momento en que pueda reunirme y liberar este anhelo contigo.",
    "A través del anhelo turbulento en mi corazón, a veces realmente necesito tu abrazo amoroso.",
    "En la noche fría, ya no recuerdo; Cuantas veces pienso en ti también te extraño.",
    "Extrañarte es como la lluvia que llega de repente y dura mucho tiempo. E incluso después de que paró la lluvia, todavía te extraño.",
    "Desde que te conocí, siempre quise aprender, aprender a ser lo mejor para ti.",
    "¿Conoces la diferencia entre tu lápiz y tu cara? Si el lápiz de escribir se puede borrar, pero si tu cara nada se podrá borrar de mi mente.",
    "No es el Examen Nacional de mañana lo que me tiene que preocupar, sino la prueba de vida por la que pasé después de que me dejaste.",
    "Una cosa que me hace feliz en la escuela es que puedo ver tu sonrisa todos los días.",
    "¿Sabes la diferencia entre ir a la escuela e ir a tu casa? Si vas a la escuela, definitivamente llevare un libro y un bolígrafo, pero si vas a tu casa, solo levare mi corazón y mi amor.",
    "No estoy triste si mañana es lunes, estoy triste si no te veo.",
    "Mis momentos de amor son perpendiculares a tus momentos de amor. Haciendo de nuestro amor un punto de equilibrio perfecto.",
    "Estoy dispuesto a participar en una carrera de atletismo alrededor del mundo, siempre y cuando seas la línea de meta.",
    "Mi tarea es extrañarte. Más fuerte que las Matemáticas, más amplio que la Física, más fuerte que la Biología.",
    "Mi amor por ti es como un metabolismo, que no para hasta morir.",
    "Si el jelangkung es como tú, ven a buscarme, te llevaré a casa.",
    "Como lo que me gusta siempre que sea contigo, incluso comer hígado.",
    "El amor es como una sentencia de muerte. Si no disparas, te cuelgas.",
    "Amarte es como una droga: una vez que intentas ser adicto, no intentas volverte curioso, deja que me vuelva adicto.",
    "Lo que más me gusta es picar porque picar es delicioso. Especialmente tenerte completamente...",
    "Este mundo nos pertenece a los dos. Los otros solo están alquilando.",
    "Para mí, todos esos días son martes. Martes en el Cielo cuando esté cerca de ti...",
    "¿Y si los dos nos convertimos en una banda de delincuentes? Yo robé tu corazón y tú robaste el mío.",
    "Eres como el café que tomé esta mañana. Amargo, pero adictivo.",
    "A menudo estoy celoso de tu lápiz labial. Él puede besarte todos los días, desde la mañana hasta la noche.",
    "Solo escuchar tu nombre puede hacerme sonreír como un tonto.",
    "Sé que tu novia no es la única, pero no me gusta solo a mí.",
    "Desde que dejé de esperarte, no me entusiasma todo..",
    "Contigo enamorarse es el desamor más intencionado.",
    "Es muy difícil sentir la felicidad de la vida sin ti a mi lado.",
    "A través del anhelo turbulento en mi corazón, a veces realmente necesito tu abrazo amoroso.",
    "Si sabes, hasta ahora te sigo amando.",
    "A veces envidio a las cometas... las cuerdas simplemente se rompen, todavía están siendo perseguidas y no quieren que otras personas se las lleven...",
    "No sabía lo que era el amor, hasta que finalmente te conocí. Pero, en ese momento supe lo que se siente tener el corazón roto..",
    "Perseguir es agotador, pero aún más cansado esperar\nEsperar a que te des cuenta de mi existencia...",
    "No dejes de amar solo porque te han lastimado. Porque no hay arcoíris sin lluvia, no hay amor verdadero sin lágrimas.",
    "Tengo un millón de razones para olvidarte, pero nada puede obligarme a dejar de amarte.",
    "A veces alguien se siente tan estúpido solo por amar a alguien.",
    "Eres el mejor desamor del que nunca me arrepentiré.",
    "No es que no valga la pena la espera, es que muchas veces da falsas esperanzas.",
    "Una parte de mí me duele, al recordarte tan cerca, pero intocable.",
    "Lo mejor de amar a alguien es orar en secreto por ellos.",
    "Desearía poder deshacerme de este sentimiento tan pronto como te perdí.",
    "Por amor nos engañamos a nosotros mismos. Intentar ser fuerte resulta ser deshonroso.",
    "Piensa en mi como tu hogar, si vas ya sabes a donde ir. Quédarte cuando quieras y irte si estás aburrida... 😢",
    "Estoy confundido, ¿debería estar decepcionado o no? Si estoy decepcionado, ¿quién soy yo para él?\n\nSi no estoy decepcionado, pero espero sus palabras.",
    "Mi anhelo es como una rama que permanece en pie, aunque ya no haya más hojas que la acompañen, hasta que finalmente se seca, se quiebra y muere.",
    "Supongo que ahora solo somos dos extraños con los mismos recuerdos.",
    "Déjame odiarte aunque solo sea por unos minutos, para que no sea muy difícil olvidarte.",
    "Te amo con todo mi corazón, pero compartes tus sentimientos con otras personas.",
    "Amarte podría romperme, pero de alguna manera dejarte no me arregló.",
    "Eres lo primero y lo más importante en mi vida. Pero, soy el segundo después de el.",
    "Si solo podemos encontrarnos en un sueño, quiero dormir y no despertar.",
    "Verte feliz es mi felicidad, aunque tú seas feliz sin mí.",
    "A veces envidio las cosas. No tiene sabor, pero siempre se necesita. En contraste conmigo que tengo sentimientos, pero fui abandonada e ignorada...",
    "Bagaimana mungkin aku berpindah jika hanya padamu hatiku bersinggah?",
    "Tus recuerdos son como mi hogar. Para que cada vez que mi mente divague, seguro que los extremos siempre volverán a ti.",
    "¿Por qué son útiles los pañuelos? Porque el amor nunca se seca. -Sujiwo Tejo",
    "Si amarte es un error, bien, déjame seguir equivocándome.",
    "Desde que te conocí, he querido aprender más. Aprendiendo a ser lo mejor para ti.",
    "Algunos actúan estúpidos solo para verte sonreír. Y estaba feliz por eso.",
    "No soy una buena persona, pero aprenderé a ser lo mejor para ti.",
    "No morimos, pero son las heridas las que nos impiden caminar como antes.",
    "Tu presencia es como una taza de café que necesito todas las mañanas, lo que puede alentarme a seguir entusiasmado con el día.",
    "Tengo muchas ganas de darte el mundo. Pero como eso es imposible, entonces te daré lo más importante de mi vida, que es mi mundo.",
    "Es mejor ser gracioso pero dulce, en lugar de pretender ser romántico pero tener un final trágico..",
    "Ben terminó sin decepcionarse, Dewe tenía que saber cuándo esperar y cuándo estancarse.",
    "Te amo porque todo el universo conspiró para que llegase hasta tí'.",
    "No es necesario ser hermoso y rico, estoy bastante seguro de que has sido amable conmigo.",
    "Mi amor por ti es como una cámara, el enfoque en ti es como otro borrón.",
    "Todos las noches sueño contigo, y es triste despertarse.",
    "No verte durante 30 días se siente como un mes.",
    "En una encuesta un 86% de los hombres afirmaron no poder vivir sin las mujer y un 27%  de las mujeres afirmaron no poder vivir sin un hombre",
    "Ojalá pudiera jugar el tiempo. Para que pueda encontrarte más rápido. Ben Lewih extendió mi tiempo para vivir contigo.",
    "Nunca supe lo que era el amor, excepto cuando te conocí.",
    "Aa el amor por ti no desaparecerá incluso si me se casa de nuevo.",
    "Mi paciencia es limitada, pero mi amor por ti es infinito..",
    "Kanyah no se desvanecerá incluso con Bayclean.",
    "Increíbles recuerdos de estar junto a ti, roble, luego recordado hasta el olvido..",
    "No podré vivir solo, necesito la ayuda de otra persona.",
    "Derrota aa al neg como un banquero para cobrar deudas (hayoh mumuntil).",
    "Cálmate, mi amor es como una canción de krispatih; No roto por el tiempo.",
    "No soy la persona perfecta para ti, ni soy el mejor para ti. Pero para estar seguro, soy la única persona que continúa recordándote.",
    "Solo la red perdida, no.",
    "Por que das falsas esperanzas",
    "Mis enemigos son aquellos que también quieren tenerte.",
    "Muchos siempre están ahí, pero si eres el único que quiero, ¿entonces qué?",
    "Mis horas de sueño están arruinadas por el anhelo.",
    "Basta que China esté lejos, no nos amen.",
    "Lo importante es tu felicidad, yo no soy importante..",
    "Mi único deseo es ser amado por ti..",
    "Yo sin ti es como una ambulancia sin wiuw wiuw wiuw.",
    "Quiero una loli."
]
